import dotenv from "dotenv";

dotenv.config();

const {
    DISCORD_TOKEN,
    DISCORD_CLIENT_ID,
    DISCORD_DEV_GUILD_ID,
    DISCORD_CATS_SHIP_GUILD_ID,
    DEV_RADIO_CHANNEL_ID,
    RADIO_CHANNEL_ID,
    CREATOR_ID,
    ADMIN_ID,
    PERMISSIVE_ROLE_ID,
    DEV_PERMISSIVE_ROLE_ID,
} = process.env;

if (
    !DISCORD_TOKEN ||
    !DISCORD_CLIENT_ID ||
    !DISCORD_DEV_GUILD_ID ||
    !DISCORD_CATS_SHIP_GUILD_ID ||
    !DEV_RADIO_CHANNEL_ID ||
    !RADIO_CHANNEL_ID ||
    !CREATOR_ID ||
    !ADMIN_ID ||
    !PERMISSIVE_ROLE_ID ||
    !DEV_PERMISSIVE_ROLE_ID
) {
    throw new Error("Missing environment variables");
}

export const config = {
    DISCORD_TOKEN,
    DISCORD_CLIENT_ID,
    DISCORD_DEV_GUILD_ID,
    DISCORD_CATS_SHIP_GUILD_ID,
    DEV_RADIO_CHANNEL_ID,
    RADIO_CHANNEL_ID,
    CREATOR_ID,
    ADMIN_ID,
    PERMISSIVE_ROLE_ID,
    DEV_PERMISSIVE_ROLE_ID,
};
